name: arb
description: A package that understands .arb files.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl_translation:
  path:
  test:

dev_dependencies:
  intl:
  pedantic: 1.9.0
